### ISSUE TITLE
grouped lights won't change color at the same time

### ISSUE THREAD

**Issue by badstraw360** [sidoh/esp8266_milight_hub#250]
If I combine multiple lights into one entity to make group and run an automation (with a scene), the lights turn on and change color one after the other. Is it possible to make the lights turn on and change color at the same time like one single light? I tried to make a group, and I even tried to use the new "light group" component but the outcome is the same, the lights change color one by one. 

```
light:
  - platform: group
      name: downstairs
      entities:
        - light.hall
        - light.kitchen
        - light.tv
```
```
scenes:
  - name: party
    entities:
      light.downstairs:
        state: on
        rgb_color: [140,90,255]
        brightness_pct: 80
```

```
automation:
  - alias: "SONOS play"
      trigger:
        - platform: state
          entity_id: media_player.sonos
          from: 'idle'
          to: 'playing'
      action:
        service: scene.turn_on
        entity_id: scene.party

```
I'm not sure if that is a problem with my setup, or if it's a limitation of the protocol.  

Thanks for this great piece of software, it's really awesome. :)
