### ISSUE TITLE
MQTT configuration is turning off all the lamps

### ISSUE THREAD

**Issue by EdgardosReis** [sidoh/esp8266_milight_hub#251]
Hello! First of all thanks for this awesome project.

So, about my issue, I really don't know where this problem came from. Actually I think that is not an issue with this project but I cannot explain either...

I've this 3 groups for now:
Desk lamp model FUT015 (8W RGB+CCT) : 
0x1112/rgb_cct/4

Living Room Back a bunch of FUT103 (4W GU10 RGB+CCT):  
0x1112/rgb_cct/2

Bedroom Ceiling FUT105 (12W RGB+CCT): 
0x1131/fut089/1

I've this configured in Home Assistant as MQTT lights and an Automation to forward the commands from milight remote to update HASS states. Something identical of the configurations described in the guides of this project.

My HASS lights configuration:

```
light: 
  - name: "Bedroom Ceiling"
    command_topic: milight/commands/0x1131/fut089/1
    state_topic: milight/states/0x1131/fut089/1
    <<: &MILIGHT_PARAMS
      platform: mqtt_json
      color_temp: true
      rgb: true
      brightness: true
      optimistic: false
  - name: "Living Room Back"
    command_topic: milight/commands/0x1112/rgb_cct/2
    state_topic: milight/states/0x1112/rgb_cct/2
    <<: *MILIGHT_PARAMS
  - name: "Desk"
    command_topic: milight/commands/0x1112/rgb_cct/4
    state_topic: milight/states/0x1112/rgb_cct/4
    <<: *MILIGHT_PARAMS
```
	
and forward automation:

```
- alias: MiLight Forwarder
  trigger:
    platform: mqtt
    topic: "milight/updates/0xD86/rgb_cct/+"
  action:
    - service: mqtt.publish
      data_template:
        topic: "milight/commands/0x1112/rgb_cct/{{ trigger.topic.split('/')[4] }}"
        payload_template: >
          {{ trigger.payload }}
```

Everything is working fine except for the weird behavior of the Desk lamp.
when i have this 3 groups turned on and I switch Desk lamp off from the Milight remote or from HASS front end, all the other 2 groups turn off also.

This is the mqtt topics published when I turn off this lamp:

```
milight/updates/0xD86/rgb_cct/4
milight/commands/0x1112/rgb_cct/4
milight/states/0xD86/rgb_cct/4
milight/updates/0x1112/rgb_cct/4
milight/states/0x1112/rgb_cct/4
milight/commands/0x1112/rgb_cct/4
milight/commands/0x1131/fut089/1
milight/commands/0x1112/rgb_cct/2
milight/updates/0x1112/rgb_cct/4
milight/updates/0x1131/fut089/1
milight/updates/0x1112/rgb_cct/2
milight/states/0x1131/fut089/1
milight/states/0x1112/rgb_cct/2
```

0xD86 is the deviceId from my milight remote and makes no sense for me the topics from line 6 to the end. It seems that something is triggering the "commands" topic of all the configured HASS ligths.

Any idea of what's happening?
