### ISSUE TITLE
Can't reset color to white if brightness not at 100% in Home Assistant

### ISSUE THREAD

**Issue by oakbrad** [sidoh/esp8266_milight_hub#258]
Not sure if this has to do with the change in color picker Home Assistant made recently, but I can't reset lights to white unless the brightness is at 100%.

This is what I see on MQTT if I change a light to green at half brightness, and then attempt to change it back to white:

```
lights/commands/0x2000/rgbw/4 {"state": "ON", "color": {"r": 0, "g": 133, "b": 0, "x": 0.172, "y": 0.747}}
lights/updates/0x2000/rgbw/4 {"state":"ON"}
lights/updates/0x2000/rgbw/4 {"hue":120}
lights/states/0x2000/rgbw/4 {"state":"ON","status":"ON","brightness":133,"level":52,"bulb_mode":"color","color":{"r":0,"g":255,"b":0}}
lights/commands/0x2000/rgbw/4 {"state": "ON", "color": {"r": 133, "g": 133, "b": 133, "x": 0.32, "y": 0.336}}
lights/updates/0x2000/rgbw/4 {"state":"ON"}
lights/updates/0x2000/rgbw/4 {"hue":0}
lights/states/0x2000/rgbw/4 {"state":"ON","status":"ON","brightness":133,"level":52,"bulb_mode":"color","color":{"r":255,"g":0,"b":0}}
```

This sets the bulb to red. If I set the brightness to 100% and then click the white in the HA interface it works as expected.

```
lights/commands/0x2000/rgbw/4 {"state": "ON", "brightness": 255}
lights/updates/0x2000/rgbw/4 {"state":"ON"}
lights/updates/0x2000/rgbw/4 {"brightness":255}
lights/states/0x2000/rgbw/4 {"state":"ON","status":"ON","brightness":255,"level":100,"bulb_mode":"color","color":{"r":255,"g":0,"b":0}}
lights/commands/0x2000/rgbw/4 {"state": "ON", "color": {"r": 255, "g": 255, "b": 255, "x": 0.32, "y": 0.336}}
lights/updates/0x2000/rgbw/4 {"state":"ON"}
lights/updates/0x2000/rgbw/4 {"command":"white_mode"}
```
I am using "computed_color" in the MiLight hub settings and my HA config looks like:

```
- platform: mqtt_json
  name: 'Office Pendant'
  state_topic: 'lights/states/0x2000/rgbw/4'
  command_topic: 'lights/commands/0x2000/rgbw/4'
  brightness: true
  rgb: true
  optimistic: false
  qos: 0
  effect: true
  effect_list:
    - white_mode
    - night_mode
    - 0 # rainbow disco
    - 1 # white glow
    - 2 # RGB glow
    - 3 # color cycle
    - 4 # RGB cycle
    - 5 # red flash
    - 6 # green flash
    - 7 # blue flash
    - 8 # loop all effects
```

I did upgrade both HA and the MiLight hub to the latest recently so I don't know if this is related to that and I messed something up. 

In the first MQTT quote above it looks like it is attempting to translate back to white at the correct brightness, but sending G and B as 0 so it comes back red.
