### ISSUE TITLE
MQTT state_topic update not affected by group ALL

### ISSUE THREAD

**Issue by vansoest** [sidoh/esp8266_milight_hub#318]
MQTT state_topic update not affected by group ALL but by groups 1-4.

I send state on to 0 = ALL and groups 1-4:
```
$ mosquitto_pub -V mqttv311 -h 127.0.0.1 -t "/milight/commands/0x2/rgb_cct/0" -m '{"state":"ON"}' 
$ mosquitto_pub -V mqttv311 -h 127.0.0.1 -t "/milight/commands/0x2/rgb_cct/1" -m '{"state":"ON"}'
$ mosquitto_pub -V mqttv311 -h 127.0.0.1 -t "/milight/commands/0x2/rgb_cct/2" -m '{"state":"ON"}'
$ mosquitto_pub -V mqttv311 -h 127.0.0.1 -t "/milight/commands/0x2/rgb_cct/3" -m '{"state":"ON"}'
$ mosquitto_pub -V mqttv311 -h 127.0.0.1 -t "/milight/commands/0x2/rgb_cct/4" -m '{"state":"ON"}'
```

But I got only the state update for group_ids 1-4, group 0 is not affected:
`$ mosquitto_sub -v -V mqttv311 -t "/milight/state/+/+/+"`:
```
/milight/state/0x2/rgb_cct/1 {"state":"ON","brightness":255,"color_temp":257,"bulb_mode":"white","color":{"r":255,"g":255,"b":255},"effect":"white_mode","device_id":2,"group_id":1}
/milight/state/0x2/rgb_cct/2 {"state":"ON","brightness":255,"color_temp":259,"bulb_mode":"white","color":{"r":255,"g":255,"b":255},"effect":"white_mode","device_id":2,"group_id":2}
/milight/state/0x2/rgb_cct/3 {"state":"ON","brightness":255,"color_temp":259,"bulb_mode":"white","color":{"r":255,"g":255,"b":255},"effect":"white_mode","device_id":2,"group_id":3}
/milight/state/0x2/rgb_cct/4 {"state":"ON","brightness":255,"color_temp":259,"bulb_mode":"white","color":{"r":255,"g":255,"b":255},"effect":"white_mode","device_id":2,"group_id":4}
```

## Environment
MQTT is configured as follow:
MQTT topic pattern: `/milight/commands/:device_id/:device_type/:group_id`
MQTT update pattern: `/milight/updates/:device_id/:device_type/:group_id`
MQTT state pattern: `/milight/state/:device_id/:device_type/:group_id`

milight_hub version: **1.8.1**

## Context
The light switch in home assisant for the group ALL to controll all 4 bubls has always the value FALSE, because the mqtt state is never published. The bulbs 1-4 are working perfectly in home assisant.

But in the past all worked like a charm. Probably a homeassisant update change, probably a bug in this bridge?

## Home assistant configuration

![selection_116](https://user-images.githubusercontent.com/574578/44299073-6464a100-a2ef-11e8-9e94-898b271534b8.png)

### Configuration YAML snippet
```
light:
  - name: Livingroom  
    state_topic: "/milight/state/0x1/rgb_cct/0"
    command_topic: "/milight/commands/0x1/rgb_cct/0"
    <<: &MILIGHT_PARAMS        
      platform: mqtt_json      
      color_temp: true         
      rgb: true
      brightness: true         
      effect: true             
      effect_list:             
        - white_mode           
        - night_mode           
        - 0
        - 1
  - name: Bedroom
    state_topic: "/milight/state/0x2/rgb_cct/0"
    command_topic: "/milight/commands/0x2/rgb_cct/0"
    <<: *MILIGHT_PARAMS
  - name: Bedroom 1
    state_topic: "/milight/state/0x2/rgb_cct/1"
    command_topic: "/milight/commands/0x2/rgb_cct/1"
    <<: *MILIGHT_PARAMS
  - name: Bedroom 2
    state_topic: "/milight/state/0x2/rgb_cct/2"
    command_topic: "/milight/commands/0x2/rgb_cct/2"
    <<: *MILIGHT_PARAMS
  - name: Bedroom 3
    state_topic: "/milight/state/0x2/rgb_cct/3"
    command_topic: "/milight/commands/0x2/rgb_cct/3"
    <<: *MILIGHT_PARAMS
  - name: Bedroom 4
    state_topic: "/milight/state/0x2/rgb_cct/4"
    command_topic: "/milight/commands/0x2/rgb_cct/4"
    <<: *MILIGHT_PARAMS
```

## Conclusion

If I send a state ON/OFF via MQTT to the group all, all bulb groups from 1-4 should be updated or the 0 group should be updated or all? What do you think? Or it's already implemented but only not workingfor me?

**Comment by PetricaM** [comment]
@vansoest 

Group 0 doesn't update anymore state for groups 1-4 (or 1-8 on the FUT089/B8) https://github.com/sidoh/esp8266_milight_hub/issues/284

You can still use HA automation to sync groups 1-4 with the state of group 0 (this is also easier on the gateway as the machine running HA is likely way more powerful than an ESP8266):

```
- alias: Push Remote Group 0 state to Groups 1 - 4
  initial_state: True
  trigger:
    - platform: mqtt
      topic: 'milight/state/0x2/rgb_cct/0'
  action:
    - service: mqtt.publish
      data_template:
        topic: 'milight/state/0x2/rgb_cct/1'
        payload_template: '{{ trigger.payload }}'
    - service: mqtt.publish
      data_template:
        topic: 'milight/state/0x2/rgb_cct/2'
        payload_template: '{{ trigger.payload }}'
    - service: mqtt.publish
      data_template:
        topic: 'milight/state/0x2/rgb_cct/3'
        payload_template: '{{ trigger.payload }}'
    - service: mqtt.publish
      data_template:
        topic: 'milight/state/0x2/rgb_cct/4'
        payload_template: '{{ trigger.payload }}'
```
A similar automation can be used to sync multiple physical remotes (associated with one bulb) to a single light entity in HA (i.e push the state of remote 0x4/0x5/etc. to remote 0x2, which is the one was used in HA; remote 0x4/0x5 doesn't need to be defined in HA):

```
- alias: Sync physical remotes states
  initial_state: True
  trigger:
    - platform: mqtt
      topic: 'milight/state/0x4/rgb_cct/3'
  action:
    - service: mqtt.publish
      data_template:
        topic: 'milight/state/0x2/rgb_cct/3'
        payload_template: '{{ trigger.payload }}'
```
Some other thoughts: 
- MQTT update topic is not used in HA config; removing it would only decrease load on the gateway;
- if wanting to use the "native" effects of MiLight (called modes) then set the effects as 0 to 8 and use an automation to forward the payload which is then changed into mode:
```
#Light config
...
  effect_list: [0, 1, 2, 3, 4, 5, 6, 7, 8]
...

#Automation

- alias: Effect2Mode
  initial_state: True
  trigger:
    - platform: mqtt
      topic: 'milight/commands/+/rgb_cct/+'
  condition: 
    condition: template
    value_template: '{{ "effect" in trigger.payload }}'  
  action:
    - service: mqtt.publish
      data_template:
        topic: "milight/commands/{{ trigger.topic.split('/')[-3] }}/rgb_cct/{{ trigger.topic.split('/')[5] }}"
        payload_template: '{ "mode": {{ trigger.payload_json.effect }} }'
```

**Comment by vansoest** [comment]
Thank you for this nice workaround! I'm using it now as follow:

```
- id: milight_push_group0
  alias: Milight: Push Remote Group 0 state to Groups 1-4
  initial_state: True
  trigger:
  - platform: mqtt             
    topic: '/milight/commands/+/rgb_cct/0' 
  action:
  - service: mqtt.publish      
    data_template:             
      topic: "/milight/state/{{ trigger.topic.split('/')[-3] }}/rgb_cct/0"
      payload_template: '{{ trigger.payload }}'
      retain: True
  - service: mqtt.publish
    data_template:
      topic: "/milight/state/{{ trigger.topic.split('/')[-3] }}/rgb_cct/1"
      payload_template: '{{ trigger.payload }}'
  - service: mqtt.publish
    data_template:
      topic: "/milight/state/{{ trigger.topic.split('/')[-3] }}/rgb_cct/2"
      payload_template: '{{ trigger.payload }}'
  - service: mqtt.publish
    data_template:
      topic: "/milight/state/{{ trigger.topic.split('/')[-3] }}/rgb_cct/3"
      payload_template: '{{ trigger.payload }}'
  - service: mqtt.publish
    data_template:
      topic: "/milight/state/{{ trigger.topic.split('/')[-3] }}/rgb_cct/4"
      payload_template: '{{ trigger.payload }}'
```

Added also a payload to push the state as retain value to group 0.

**Comment by PetricaM** [comment]
Similar automations can be used to translate white_value (supported by HA) into saturation (used by ESPMH however in reverse: low white_value corresponds to high saturation and vice versa) and to convert scale for color_temp (color_temp is used by both however with different ranges: 0-370 vs. 153-500)

**Comment by sidoh** [comment]
Thanks for the super detailed report @vansoest, and @PetricaM for the detailed followup.  You're both awesome.

As Petrica points out, this is now expected.

However, I do recognize that it might result in unexpected behavior, and I'm open to making changes if folks feel like it'd be worthwhile.

**Comment by FrankZZ** [comment]
@sidoh should group 0 publish a state message for itself (I just understood it won't send a state message for 1-4 but what about 0)?

**Comment by sidoh** [comment]
I considered this in #284.  The trouble is that you can't really keep state for group 0 in a way that makes sense in every situation.  The reason for this is fundamentally that it's not a group.

Example:

* Turn group 0 "on" (turns groups 1, 2, 3, and 4 on)
* Turn groups 1-3 off individually

What, then, is the state for group 0?

I think it's just really messy to treat group 0 as a real group.  Maybe the practical implications outweigh this conceptual fuzziness, but I think we'd need more data.

**Comment by FrankZZ** [comment]
Ah, I get it. I was going to use group 0 as a workaround for the "multiple bulbs in HA light group don't turn on at the same time" and when I want I can still trigger the individual bulbs (by not using group 0 but the actual bulb group)

**Comment by PetricaM** [comment]
Hi Chris,

"Group" 0 state would be useful case wanting to set the state of multiple bulbs without going through each and every one (for 6-7 lights takes about 20 seconds in Home Assistant to set each light). 

Another case would be when having multiple lights the same room and setting different colors/intensity to each bulb (what Hue uses as scene): so have group 1 of the remote paired to light 1, group 2 to light 2, etc. For setting the scene Home Assistant would send the command to each light individually (takes about 2-3 seconds for 4 groups lights, using a 100ms delay between commands). However, for common use (about 98% of the time, thus when not trying to impress guests :) ) the four/eight groups should have the same setting. In this case, group 0 would be used to send the command and all bulbs react immediately.

The problem is that now, if sending a command that includes saturation to group 0, it activates white mode and the light flickers thus making commands from HA for group 0 quite useless (sending group 0 from a physical remote doesn't have this side effect). An workaround is to use, instead group 0 of a single remote the group 1 (or any other) of a different remote.
So pretty much the following situation:
Remote 0x1, group 1 -> Light 1
...
Remote 0x1, group 4 -> Light 4 (or even groups from 5 to 8, for FUT089)

Remote 0x2, group 1 -> Light 1, Light 2,.. Light 4

Physical vs. "virtual" remotes
For practical purposes remote 0x2 should be a physical remote (remote 0x1 can be either physical or virtual). There are several reasons for this: yelling at Alexa/Google in the middle of the night to turn on the light isn't the best approach so using the old way of pushing the button is still preferable; case of home automation software failure (from power failure or other reasons), then a virtual remote cannot be used. Also, if using a physical remote, by setting the state topic of the gateway to the one in HA ensures the light and HA are in sync. 
The above involves actual pairing of the remotes to bulbs (not merely forwarding from remote 0x2 to remote 0x1 as these  commands would take several seconds). The bad news with this is that there is a hard limit of 4 remotes to which a bulb can be associated (adding new remotes erases the old ones on a FIFO basis) so here comes in play state  forwarding.

Forwarding
It is possible to forward commands (and states) from a remote to another (it does take about half of second for the command to be recorded by the gateway, published on the MQTT as state, forwarded to the command topic, then issue the command). However, if forwarding from state topic of one gateway to its command topic, then the gateway is knocked out after about 4-5 commands as it enters into a loop (see below: I forward state topic of gateway 2 to command topic, which is the same for all gateways; if I would forward state topic of gateway 1 then after a brief period of time, none of the gateways is online)

I have 3 MiLight gateways, for reliability (in order to cover the entire home as there are some blind spots if using only one remote) set as following. Gateway 1 publishes the state which is used by HA as state for the bulbs. Gateway 2 publishes the state but forwarded only in some cases (based on defined automation).

Gateway 1:
command topic
home/milight_gw/:device_id/:device_type/:group_id

state topic
home/milight_gw/state/:device_id/:device_type/:group_id

Gateway 2:
command topic
home/milight_gw/:device_id/:device_type/:group_id

state topic
sniff/milight_gw/state/:device_id/:device_type/:group_id

Gateway 3:
command topic
home/milight_gw/:device_id/:device_type/:group_id

state topic
no state topic

Other considerations: 
- would it be possible for the gateway to send brightness equal to 1 each time the bulb is turned off? By setting brightness to 1 when bulb is powered off there would be a relatively smooth transition so that when turned on again it won't reach full brightness immediately (the bulb turns on with the last setting so case of a power failure the light would turn to full brightness when power comes back if that was the last setting; also, if using different brightness setting for day/sunset/night scenes then when turned on the light would have the setting from the previous mode). I do this now by sending first brightness 1 (then the off command) but wondering if it could be setup on the gateway.
- is it possible to send the effect to bulb with a certain time transition (slower transition) directly? Sending mode and then S- to light does slow down, however wandering if can be set directly at the slower transition pace with a command (at the moment sending slow down from the remote doesn't differentiate in the state published).

**Comment by sidoh** [comment]
Keep in mind that you can still send commands to group 0, state will just not be kept for it.

The hue/saturation thing can probably be solved for separately.  As long as you send the state in one command, it should be possible to send the appropriate command packets to the bulb.

> would it be possible for the gateway to send brightness equal to 1 each time the bulb is turned off? By setting brightness to 1 when bulb is powered off there would be a relatively smooth transition so that when turned on again it won't reach full brightness immediately (the bulb turns on with the last setting so case of a power failure the light would turn to full brightness when power comes back if that was the last setting; also, if using different brightness setting for day/sunset/night scenes then when turned on the light would have the setting from the previous mode). I do this now by sending first brightness 1 (then the off command) but wondering if it could be setup on the gateway.

Yes, possible.  The request has come up before.  It has in the past felt like it's most appropriately solved by some layer above espMH like HASS.

> is it possible to send the effect to bulb with a certain time transition (slower transition) directly? Sending mode and then S- to light does slow down, however wandering if can be set directly at the slower transition pace with a command (at the moment sending slow down from the remote doesn't differentiate in the state published).

At least for all of the milight protocols I'm familiar with, it's not possible except by spamming down 10x and then pressing up the appropriate number of times.  I implemented this for brightness/color temp for CCT bulbs and it has all sorts of funky quirks.

**Comment by PetricaM** [comment]
On a side note, would it be able to add some new custom fields to state topic? :)
- white_value (used by HA, similar to saturation except completely different :D : high saturation corresponds to low whites, low saturation/high whites);
- modified color temp to match the scale in HA (something like HA ct).

Current version can be used with some custom automation between HA and gateway back and forth:
- for color temp: (((trigger.payload_json.color_temp - 153 )*370)/347) and ((trigger.payload_json.color_temp/370)*347)+153); 
- for saturation (((255 - (trigger.payload_json.white_value | int)) / 2.55)  and (((100 - (trigger.payload_json.saturation | int)) * 2.55) respectively
However, it is quite nagging as it require intermediate MQTT topics that add up to the delay of the commands.

**Comment by boschr** [comment]
This breaking change is really confusing and annoying. Still want to use group 0 to toggle all my groups. I'm not an HA expert, only did some small experimental, this is my situation:

Currently i'm not using the `automations.yaml` but just the `configuration.yaml` like this:

```
light:
  - platform: mqtt_json
    name: XXX
    state_topic: milight/states/0x6F/rgb_cct/0
    command_topic: milight/0x6F/rgb_cct/0
    brightness: true
    rgb: true
```

It's not clear to me if i still can use this setup.
