### ISSUE TITLE
Memory leak - causes settings to be randomly cleared

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#600]
### Describe the bug

After restore settings I see all the information. But after a while everything is gone in WebUI, strange enough... everything is still working inside HA to control the lights

### Steps to reproduce

Restore settings, after while goto the WebGUI and everything is gone again.

### Expected behavior

After restore all settings keep in memory.

### Additional info

I don't use anymore device name because that gives some issues as well.

#### Firmware version
1.10.5 (nodemcuv2)

#### Output of http://milight-hub.local/about:  **When WebGUI is empty**
```
{"firmware":"milight-hub","version":"1.10.5","ip_address":"192.168.xxx.xxx","reset_reason":"Software/System restart","variant":"nodemcuv2","free_heap":6616,"arduino_version":"2_4_2","queue_stats":{"length":0,"dropped_packets":0}}
```
#### Output of http://milight-hub.local/about:  **When WebGUI is normal**
```
{"firmware":"milight-hub","version":"1.10.5","ip_address":"192.168.xxx.xxx","reset_reason":"Software/System restart","variant":"nodemcuv2","free_heap":16016,"arduino_version":"2_4_2","queue_stats":{"length":0,"dropped_packets":0}}
```

#### Output of http://milight-hub.local/settings **When WebGUI is empty**
```
{}
```
#### Output of http://milight-hub.local/settings **When WebGUI is normal**

```
{"admin_username":"","admin_password":"","ce_pin":16,"csn_pin":15,"reset_pin":0,"led_pin":-2,"radio_interface_type":"nRF24","packet_repeats":50,"http_repeat_factor":1,"auto_restart_period":0,"mqtt_server":"192.168.xxx.xxx:1883","mqtt_username":"USERNAME","mqtt_password":"PASSWORD","mqtt_topic_pattern":"milight/:device_id/:device_type/:group_id","mqtt_update_topic_pattern":"milight/updates/:hex_device_id/:device_type/:group_id","mqtt_state_topic_pattern":"milight/states/:hex_device_id/:device_type/:group_id","mqtt_client_status_topic":"milight/client_status","simple_mqtt_client_status":true,"discovery_port":48899,"listen_repeats":0,"state_flush_interval":100,"mqtt_state_rate_limit":500,"packet_repeat_throttle_sensitivity":50,"packet_repeat_throttle_threshold":500,"packet_repeat_minimum":50,"enable_automatic_mode_switching":false,"led_mode_wifi_config":"Fast toggle","led_mode_wifi_failed":"Fast blip","led_mode_operating":"Slow toggle","led_mode_packet":"Fast blip","led_mode_packet_count":4,"hostname":"MilightHub","rf24_power_level":"MAX","rf24_listen_channel":"LOW","wifi_static_ip":"192.68.xxx.xxx","wifi_static_ip_gateway":"192.168.xxx.xxx","wifi_static_ip_netmask":"255.255.255.0","packet_repeats_per_loop":50,"home_assistant_discovery_prefix":"","wifi_mode":"n","default_transition_period":500,"rf24_channels":["LOW","MID","HIGH"],"device_ids":[43681,43682,43683,43684,43690,43691,43692,43693,43694,43695,43706,43707],"gateway_configs":[],"group_state_fields":["state","status","brightness","level","hue","saturation","color","mode","kelvin","color_temp","bulb_mode","computed_color","effect","device_id","group_id","device_type"],"group_id_aliases":{}}
```

**Comment by sidoh** [comment]
Thanks for reporting and providing the info.  Left a comment on #601, guessing this is related.  

This is very interesting:

```
{"free_heap":6616}
```

that's critically low and very likely to cause funky problems.  Validates the hypothesis that there's a leak and something screwy is happening when heap is low.

Next steps are:

1. Find what's causing settings to clear when heap is low, add as much guarding around that as possible.
1. Potentially add auto-restart logic if heap gets too low
1. Find the source of the leak (my best guess is the packet queue, which is the only place i can think of where memory is regularly allocated dynamically)
1. Figure out ways to clear up heap.  16KB steady-state is pretty crappy.

**Comment by poudenes** [comment]
only thing what I can think about is next: I use Circadian Light option in HA. When I have some lights on and reboot my HA because of some changes, it will send lots of data to Hub.

When HA is booted, it will change all lights to right Kelvin, Brightness. In meanwhile it also receive all kind of mqtt information because its update the settings in HA also.

I realise that this clear settings never happend before (only at the moment I tried to add for every light a device name) but leave that and everything was ok. Last moment I try the Circadian Light option for a better healthy life... I will disable that for while and do same things (reboot HA sometimes because of changes). See what happen

Sorry for my bad explanation in English.... :) Im a dutchie!

**Comment by sidoh** [comment]
Definitely interesting.  If you're able to find a way to reliably reproduce a memory leak (just check `free_heap` from `/about`), that'd be a huge help.  Perhaps restarting HA a few times?

**Comment by poudenes** [comment]
@sidoh When im 2 days off I will do some tests. If HA is fail then I have time to repair it before my partner gets home in a dark house :)

**Comment by sidoh** [comment]
Great, much appreciated.

Hah!  I can relate.  Can't tell you how many times I've accidentally turned the lamp in the other room purple while testing things.

If it's possible for you to share your HA configs, or instructions on how to set up Circadian Light, that might help as well.

How many milight groups to you have set up in HA?

**Comment by poudenes** [comment]
@sidoh Here's my configuration: https://github.com/poudenes/homeassistant
Here example to add Circadian Light

```
###########################################################################################
#
# CIRCADIAN LIGHTING
#
# https://github.com/claytonjn/hass-circadian_lighting
#
###########################################################################################
---
platform: circadian_lighting
name: "Circadian Bathroom"
lights_ct:
  - light.bathroom_all
disable_brightness_adjust: true
```
I have 32 individual groups in HA and 6 group 0 in HA

Im using the Patch for correct updates using MQTT from HA to Milight Hub:

```
###########################################################################################
#
# PATCH WHEN GROUP 0 IS ON OR OFF THE CORRECT STATUS WILL SEND TO MILIGHT HUB FOR ALL LIGHTS INSIDE GROUP
#
###########################################################################################

- alias: "Patches - MiLight Bedroom Group 0"
  initial_state: "true"
  trigger:

    platform: mqtt
    topic: "milight/states/0xAABA/rgb_cct/1"

  action:
    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAAA/rgb_cct/1"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAAA/rgb_cct/2"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAAA/rgb_cct/3"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAAA/rgb_cct/4"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAAB/rgb_cct/1"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data_template:
        topic: "milight/states/0xAAAB/rgb_cct/2"
        payload_template: "{{ trigger.payload }}"
```

I have 7 of those patches.

So I can imagine when Circadian Light is on for "bedroom_all" (group 0) it will update all others, but also all individual lights will controlled by Circadian Light.

There is a bunch of MQTT traffic I guess
