### ISSUE TITLE
JSON Output for Home Assistant

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#773]
The MQTT Light config in Home Assistant has been changed/improved. 
https://www.home-assistant.io/integrations/light.mqtt/

They use follow JSON Schema:

{
  "brightness": 255,
  "color_mode": "rgb",
  "color_temp": 155,
  "color": {
    "r": 255,
    "g": 180,
    "b": 200,
    "c": 100,
    "w": 50,
    "x": 0.406,
    "y": 0.301,
    "h": 344.0,
    "s": 29.412
  },
  "effect": "colorloop",
  "state": "ON",
  "transition": 2,
}

Thats different then Milight_hub sends. 
Im not technical enought to understand the difference, but it seems there is a mismatch...

Can you look into this?

**Comment by poudenes** [comment]
For example:
**HS Color (hue)**
```
mqtt:
  light:
    - schema: json
      name: mqtt_json_hs_light
      state_topic: "home/light"
      command_topic: "home/light/set"
      color_mode: true
      supported_color_modes: ["hs"]
```
HA expect:
```
{
  "state": "ON",
  "color_mode": "hs",
  "color": {
    "h": 24.0,
    "s": 100.0
  }
}
```

**Comment by devax** [comment]
Sorry for piggybacking, but my problem seems somehow related.
Home Assistant is pushing me to update my manual configuration that is currently under 
```yaml
light:
  platform: mqtt
  ...
```
to the new format which should be
```yaml
mqtt:
  light:
    ....
```
The wiki seems to be outdated, as it still shows the legacy configuration (which seems to be unsupported with the upcoming version 2022.12): https://github.com/sidoh/esp8266_milight_hub/wiki/HomeAssistant#hass

Can I find somewhere a working example for the new configuration?

My confusion starts when trying to setup the new configuration in VS Code, as it's giving me a lot of red lines:
![image](https://user-images.githubusercontent.com/22288651/203381468-cd6e1f72-b244-4363-8240-8fa426a74b36.png)

I would appreciate if someone could point me to a good starting guide or to a working example.

Or is this new configuration not supported by milight hub?
