### ISSUE TITLE
MQTT Light in Home Assistant 2022.10.x

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#780]
Hi All,

I have some problems with MQTT lights and Home Assistant when MQTT Broker is for a moment offline and come online again.
When this happen some lights went on and others keep off. I really don't know how to solve this.

I cleared MQTT broker one time but didn't work. Retain is off but its getting me crazy. 
Below the config how I add the lights into HA:

```
light:
  - name: "Livingroom All"
    unique_id: "68ee8212-e45a-4898-aa66-42d7f16358e8"
    command_topic: "milight/0xAAAC/rgb_cct/0"
    state_topic: "milight/states/0xAAAC/rgb_cct/0"
    retain: true
    <<: &MILIGHT_PARAMS
      schema: "json"
      availability_topic: "milight/client_status"
      payload_available: "connected"
      payload_not_available: "disconnected"
      brightness: true
      effect: true
      effect_list:
        - "night_mode"
        - "white_mode"
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
      rgb: true
      color_temp: true
      max_mireds: 370
      min_mireds: 153
```

Because some lights are in a group (all) that's /0 instead of /1, /2, /3 or /4 for the group. I use this to patch all separate groups with same topic information (to sync Milight hub with HA)

```
- id: "0596ec6b-233a-4e44-a107-51004000f38a"
  alias: "Patches - MiLight Livingroom Group 0"
  mode: restart
  initial_state: true
  trigger:
    - platform: mqtt
      topic: "milight/states/0xAAAC/rgb_cct/0"

  condition: []

  action:
    - service: mqtt.publish
      data:
        topic: "milight/states/0xAAAC/rgb_cct/1"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data:
        topic: "milight/states/0xAAAC/rgb_cct/2"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data:
        topic: "milight/states/0xAAAC/rgb_cct/3"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data:
        topic: "milight/states/0xAAAC/rgb_cct/4"
        payload_template: "{{ trigger.payload }}"

    # LIVINGROOM WALL WINDOWS BULBS
    - service: mqtt.publish
      data:
        topic: "milight/states/0xAABB/rgb_cct/1"
        payload_template: "{{ trigger.payload }}"

    - service: mqtt.publish
      data:
        topic: "milight/states/0xAABB/rgb_cct/2"
        payload_template: "{{ trigger.payload }}"
```

So when I turn on or off or change color, kelvin in group 0 all other groups 1,2,3 and 4 also changed nicely.
Now you know the setup the question:

When I turn off all lights and the MQTT Broker goes offline and online again some lights go on. (look like the status is still on in MQTT broker)

I hope someone understand what I mean....
