### ISSUE TITLE
Color Status not updating on Home Assistant

### ISSUE THREAD

**Issue by ArshSoni** [sidoh/esp8266_milight_hub#852]
### Describe the bug

After updating MilightHub to 1.13.0, Home Assistant no longer shows the correct brightness/color attributes on entities. 

<img width="488" alt="Screenshot 2024-11-23 at 17 33 55" src="https://github.com/user-attachments/assets/873a7c16-3a5b-4ef3-aefe-96732dedb5fc">

<img width="387" alt="Screenshot 2024-11-23 at 17 34 13" src="https://github.com/user-attachments/assets/9571070f-c9f7-4d9b-8201-e9ece4c34ca3">

#### Output of http://milight-hub.local/about

```json
"... /about output. put between the ```s"
```

#### Output of http://milight-hub.local/settings

```json
"... /settings output. put between the ```s"
```

**Comment by Jojo-1000** [comment]
Hi, I am using it with home assistant on this version and the color is updating correctly. Can you check what MQTT is received?
You can subscribe to `milight/state/#` on the device settings for MQTT to see what it gets.
Mine looks like this: Topic `milight/state/0xA4A8/rgb_cct/1`
```
{
    "state": "ON",
    "brightness": 82,
    "color": {
        "r": 133,
        "g": 255,
        "b": 119
    },
    "color_mode": "rgb"
}
```

The one thing that doesn't work is if you control multiple lights at once using the controls for all.

**Comment by Jojo-1000** [comment]
You should try `"color_mode": "color_temp"` instead of "white" if you have not yet. It might be that homeassistant thinks they are in ON/OFF mode, so they don't support brightness.

Then there might be something wrong with the configuration. If you go on the milight-hub device there is an advanced option "MQTT Info" which should have the internal configuration values for the lights. Mine looks like this:
<details>

```
MQTT discovery data:
Topic: homeassistant/light/milight_hub_.../fut089_0xAF77_1/config
```
```yaml
schema: json
effect: true
device_class: light
payload_not_available: disconnected
max_mireds: 370
name: LED CCT
unique_id: CFC714-LED CCT
payload_available: connected
state_topic: milight/state/0xAF77/fut089/1
min_mireds: 153
device:
  identifiers: '...'
  name: milight-hub
  model: d1_mini
  manufacturer: espressif
  sw_version: esp8266_milight_hub v1.13.0-11-g1ac8a09
  configuration_url: http://192.168.178.111
effect_list:
  - night_mode
  - white_mode
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
supported_color_modes:
  - rgb
  - color_temp
availability_topic: milight/client_status
command_topic: milight/commands/0xAF77/fut089/1
```
</details>

I would expect that your light should have `supported_color_modes` matching your devices, so the CCT only has one, which might be why it works without specifying it.
